services:
  flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app/logs:/app/logs
    env_file:
      - ./app/.env

  replay-engine:
    build:
      context: ./replay-engine
      dockerfile: Dockerfile
    volumes:
      - ./app/logs:/app/logs
    environment:
      - DLTRF_LOG_PATH=logs/events.log