version: "3.8"

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app              # Mount local code into container
      - ./logs:/app/logs    # Mount logs folder for persistence
    environment:
      - DLTRF_LOG_PATH=/app/logs/events.log
